name: Scale Sentry AI
description: AI-driven scalability simulator for pull request diffs using OpenAI models.
inputs:
  github-token:
    description: GitHub token with permissions to read PRs and post comments.
    required: true
  openai-api-key:
    description: OpenAI API key used for the analysis request.
    required: true
  openai-model:
    description: OpenAI model identifier (e.g. gpt-4o, gpt-4o-mini).
    required: false
    default: gpt-4o
  openai-max-tokens:
    description: Maximum tokens for the OpenAI completion.
    required: false
    default: "900"
  openai-temperature:
    description: Sampling temperature for OpenAI (0-1).
    required: false
    default: "0.2"
  target-language:
    description: Hint about the primary language or framework in the repository.
    required: false
    default: TypeScript
  traffic-profile:
    description: Traffic range or profile to simulate (e.g. 1k-100k requests per second).
    required: false
    default: 1k-100k requests per second
  post-comment:
    description: When true, publish the report as a pull request comment.
    required: false
    default: "true"
  write-job-summary:
    description: When true, attach the report to the workflow job summary.
    required: false
    default: "true"
outputs:
  report:
    description: Markdown report generated by the AI analysis.
runs:
  using: node20
  main: dist/index.js
branding:
  color: blue
  icon: radar
